# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hi_pb2 as hi__pb2


class HiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHi = channel.unary_unary(
        '/higrpc.Hi/SayHi',
        request_serializer=hi__pb2.HiRequest.SerializeToString,
        response_deserializer=hi__pb2.HiReply.FromString,
        )
    self.CountHi = channel.unary_unary(
        '/higrpc.Hi/CountHi',
        request_serializer=hi__pb2.HiRequest.SerializeToString,
        response_deserializer=hi__pb2.HiReply.FromString,
        )
    self.JaejinHi = channel.unary_unary(
        '/higrpc.Hi/JaejinHi',
        request_serializer=hi__pb2.HiRequest.SerializeToString,
        response_deserializer=hi__pb2.HiReply.FromString,
        )


class HiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHi(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CountHi(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def JaejinHi(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHi': grpc.unary_unary_rpc_method_handler(
          servicer.SayHi,
          request_deserializer=hi__pb2.HiRequest.FromString,
          response_serializer=hi__pb2.HiReply.SerializeToString,
      ),
      'CountHi': grpc.unary_unary_rpc_method_handler(
          servicer.CountHi,
          request_deserializer=hi__pb2.HiRequest.FromString,
          response_serializer=hi__pb2.HiReply.SerializeToString,
      ),
      'JaejinHi': grpc.unary_unary_rpc_method_handler(
          servicer.JaejinHi,
          request_deserializer=hi__pb2.HiRequest.FromString,
          response_serializer=hi__pb2.HiReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'higrpc.Hi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
